language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
global:
 - export NODE_ENV=test

env:
  global:
    - CC_TEST_REPORTER_ID=75240f524424b47cec9bc7fc047c59ef885a0790c4c3e5a9856edebbae5ef656

before_install:
- npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm run build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
- npm run coverage
script:
- npm run test
notifications:
